name: Build

on:
  pull_request:
    paths-ignore:
     - 'docs/**'
     - 'README.md'
    branches: 
      - master
  push:
    paths-ignore:
     - 'docs/**'
     - 'README.md'
    branches: 
      - master

jobs:
  build:
    
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/checkout@v3.2.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run tests
      env:
        CI: true
