name: Build

on:
  pull_request:
    paths-ignore:
     - 'docs/**'
     - 'README.md'
    branches: 
      - master
  push:
    paths-ignore:
     - 'docs/**'
     - 'README.md'
    branches: 
      - master

jobs:
  build:
    
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
    - uses: actions/checkout@v3
    - name: Pactum run
    - uses: actions/checkout@v3.2.0
      with:
      
        node-version: 16.14.0
    - run: npm install
    - run: npx mocha tests
